### ISSUE TITLE
Current track in Atom editor

### ISSUE THREAD

**Issue by benogle** [rdio/api#115]
Hey guys. I'd like to write an [atom](http://atom.io) package to display the current track of some user (me!) in atom editor.

I'm currently using [findUser](https://groups.google.com/forum/#!msg/rdio-api/I9Usd7TlalU/PwbeSK4mfz0J) method with an email address and `extras: 'lastSongPlayed,lastSongPlayTime'`. It displays:

![screen shot 2014-03-01 at 2 43 34 pm](https://f.cloud.github.com/assets/69169/2302923/328bda28-a195-11e3-9092-dedcbd71c037.png)

But it's not at all what I want. Turns out it is never the _current_ song, but the previous to current, and there is no way to tell if it is playing or not playing. 

Looks like there is a 'javascript api', that might solve my needs, but it's not public. (https://github.com/rdio/jsapi-examples/tree/master/utils)

Also, security. In order to get this info, I have to provide my api key and secret somewhere in the code. I suppose I could force a user of the package to get their own key, and store it in the config/keychain, but that sucks. 

Is there a legit way to do this? All I want is:
- display current song with some degree of accuracy
- display 'Not playing' or something when I'm not playing music
- not be a pain for the user
- not have to share my api key

Down the line, it would be cool to add pause and play functionality, but not a big deal. 

Ideally would be this flow :)
- I pop up a dialog to sign in first time through, they enter creds
- I oauth, get a token, put it in the keychain
- I use the oauth token from then on to get `currentSongPlaying`

**Comment by rknLA** [comment]
Yep, this is all stuff we're aware of.

We don't currently support a `currentPlayingSong` method in the Web Service API.  The JS API can access this info (and provide playback controls), but the interface it uses is abstracted away, so it's not something you can `curl` directly, and the API is designed for in-browser use cases.  If you're interested in hacking on it, email developersupport@rd.io with your Rdio username and we'll add you to the beta.

The security issue of shipping keys with a native app is a general problem with OAuth 1.0a that OAuth2 attempts to solve by using the implicit grant and redirect URIs.  For your particular use case, you could sandbox your API calls by proxying to a service that you run.  There's still a potential risk of people abusing your URL, but at least people would only be able to get the info that you expose, rather than run the gamut with your credentials.

**Comment by benogle** [comment]
Thanks for the response.

**Comment by dasevilla** [comment]
A developer did an integration with the Mac app: https://atom.io/packages/Rdio

**Comment by benogle** [comment]
Yep, using it!
