### ISSUE TITLE
iOS OAuth v2 Crashes

### ISSUE THREAD

**Issue by ungureanuli** [rdio/api#155]
Using the iOS Rdio SDK 3.0.2, on an iPhone with iOS 7.1.2, there are often crashes at the end of the login flow. 
Reason: objc_msgSend() selector name: respondsToSelector:
Exception Type: SIGSEGV

Thread 0 crashed with the callstack:
-[Rdio sessionLoginDidSucceed](Rdio.m:316)
__27-[RDSession getCurrentUser]_block_invoke (RDSession.m:522)

**Comment by ungureanuli** [comment]
Another similar crash (on the same device) happens when the user is canceling the login flow, by tapping the "Close" button.
Reason: objc_msgSend() selector name: respondsToSelector:
Exception Type: SIGSEGV

Thread 0 crashed with the callstack:
-Rdio loginCancelled (Rdio.m:293)
-RDAuthViewController cancel (RDAuthViewController.m:283)

**Comment by dasevilla** [comment]
My guess with this issue is that [the Rdio delegate](http://www.rdio.com/media/static/developer/ios/docs/protocol_rdio_delegate-p.html) that you registered has gone missing. When you press the cancel button we check to see if the delegate has implemented (`respondsToSelector:`) the `rdioAuthorizationCancelled`.

**Comment by ungureanuli** [comment]
Indeed the issue appeared at the second login. I was using:

>  [[Rdio alloc] initWithClientId:kRdioClientID andSecret:kRdioClientSecret delegate:self];

However by setting the delegate every time before a login, seemed to have fix the crashes (the deallocated delegate from the first initialization was indeed the issue).
Thank you Devin for your help.
