### ISSUE TITLE
Do not display an UIAlertView on authentication failure

### ISSUE THREAD

**Issue by xinsight** [rdio/api#30]
While authenticating a user token, if there is a failure (e.g. no network) an UIAlertView is displayed.

There is no way to prevent this alertview from appearing, and it is also not particularly helpful (Error: Login failed). Why did it fail? How do they know it relates to Rdio?

The `rdioAuthorizationFailed` delegate is still called, so you can ditch the alertview and let application developers to handle the error in a more useful way.

(ps - Better separation of model and views would **greatly** improve the utility of the SDK. It would be so much cleaner to simply check the rdio authentication status and then display the RDAuthViewController if and when it makes sense.)

**Comment by rknLA** [comment]
Sorry for the delayed response here, but we have a patch in review that solves this problem.  I'll post another update when we're through with the code review process.  Thanks for your patience.

**Comment by rknLA** [comment]
I'm happy to finally be able to say that this issue has been fixed in today's release of v1.2. :smiley_cat: 

If you don't change any of your code, you'll still see the login modal pop up, but the UIAlertView will not get triggered.

We're advising people to switch over to the new `authorizeUsingAccessToken` method, which does not accept a `UIViewController` argument, and does not have any UI side effects other than those that you implement yourself in the `rdioAuthorizationFailed` method.
