### ISSUE TITLE
[iOS] SDK throws C++ exceptions when playing songs

### ISSUE THREAD

**Issue by steveluscher** [rdio/api#69]
**Steps to reproduce:**

1) Clone the [sample app](https://github.com/rdio/hello-ios-playback)
2) Go into the Xcode Breakpoint Navigator (⌘6)
3) Click (+) at the bottom of the Breakpoint Navigator's column to add an "Exception Breakpoint"
4) From the "Exception" menu choose "C++" and leave everything else as it appears
5) Run the app and try to play a song.

You'll be dropped into the debugger. Clicking "continue" seven times makes the track play.

```
  0x35294:  calll  0x161baa                  ; symbol stub for: AudioQueueStart
> 0x35299:  movl   %eax, -16(%ebp)
  0x3529c:  testl  %eax, %eax
  0x3529e:  je     0x3532f                   ; MyEnqueueBuffer + 471 at AudioStreamer.m:386
```

**Comment by steveluscher** [comment]
For those of you who want to break on exceptions in your app without breaking on this (spurious?) Rdio SDK exception, simply change your "All Exceptions on throw" breakpoint to an "All Objective-C Exceptions on throw" one.

**Comment by rknLA** [comment]
This issue came up again on the Google Group.

It looks like the exceptions are getting thrown by some of Apple's `Audio Queue Service` methods (`AudioQueueStart` and `AudioQueueDispose` are the main culprits).  The exceptions seem to be occurring in situations where those methods are returning a non-null `OSStatus` value, which is to say, the methods are returning an error.

I'm not sure yet if it's something we'll be fixing in the near term, since the exceptions appear to be caught properly and do not bubble up or otherwise affect the SDK's functionality.

**Comment by dasevilla** [comment]
The latest iOS SDK contains many fixes to streaming. If you can still reproduce this issue, please reopen.

http://blog.rdio.com/developers/2015/06/ios-sdk-v302.html
